name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: _actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: _actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run format check
        run: npm run prettier

      - name: Run unit tests
        run: npm run test

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run playwright tests
        run: npm run e2e
